export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  administracao: "/administracao",
  colaboradores: "/colaboradores",
  premiosProdutividade: "/premios-produtividade",
  boletinsMedicao: "/boletins-medicao",
  documentacoes: "/documentacoes",
  cadernoVirtual: "/caderno-virtual",
  lancamentosDiarios: "/lancamentos-diarios",
  relatorios: "/relatorios",
  financeiro: "/financeiro",
  notificacoes: "/notificacoes",
  documentosFinanceiros: "/documentos-financeiros",
  perfil: "/perfil",
  configuracoes: "/Configuracoes",
};
